version: '3'

services:
  app:
    build: .
    container_name: card-game-app
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3333:3333
  redis:
    image: redis
    ports:
      - "6379:6379"
